version: "3.9"

services:
  php-fpm: 
    container_name: php_${PHP_VERSION}
    image: myphp:${PHP_VERSION}
    build: 
      context: .
      dockerfile: php:${PHP_VERSION}.dockerfile
    env_file:
      - php-dev.env
    environment:
      - PHP_IDE_CONFIG=serverName=XdebugServer
    ports:
      - "9003:9003"
      - "9000:9000"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - backend
    db:
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_DATABASE: projeto # definir aqui
        MYSQL_USER: uProjeto # definir aqui
        MYSQL_PASSWORD: sProjeto # definir aqui
        MYSQL_ROOT_PASSWORD: example # definir aqui
      ports:
        - "3306:3306"
      networks: 
        - backend

networks:
#rede interna
  default:
#rede compartilhada com host
  backend:
    driver: bridge
#rede criada fora do compose
  db:
    external:
#rede extena com alias
  mysql:
    external:
      name: mysqlnet
      
volumes:
  mysql_data:
  mysql_config:
    external:
    
extra_hosts:
  - "host.docker.internal:host-gateway"
