version: '3.1'
services:
  db_mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: db_mongo
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@db_mongo:27017/
    networks:
      - db

volumes:
  mongo:
networks:
  db:
    external: true

# docker run -it --rm mongo --help
# docker run --name some-mongo -v /my/custom:/etc/mongo -d mongo --config /etc/mongo/mongod.conf
# docker exec -it ambiente_db_mongo_1 mongo -u root -p example
