services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - dbData:/var/lib/postgresql
      - ./db_scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@email.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 8092:80
volumes:
  dbData: