services:
  keycloak:
    container_name: keycloak
    image: keycloaklocal
    build: 
      context: ./
      dockerfile: dockerfile
      args:
        DBHOST: db_keycloak
        DBUSERNAME: key
        DBPASSWORD: key
        # DBSCHEMA: key
        DBNAME: key
        HOSTNAME: localhost        
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - ./api:/api
    ports:
      - "8080:8080"
    networks:
      - db_key
  db_keycloak:
      image: postgres:15
      environment:
        POSTGRES_DB: key
        POSTGRES_USER: key
        POSTGRES_PASSWORD: key
      networks:
        - db_key
      volumes:
        - v_db_key:/var/lib/postgresql/data
      ports:
        - 5432:5432
networks:
  db_key:
  api_ieptb:
volumes:
  v_db_key: