FROM quay.io/keycloak/keycloak:latest as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES="authorization,account2,account-api,admin2,docker,scripts,token-exchange,web-authn,client-policies,par,declarative-user-profile,client-secret-rotation,step-up-authentication,recovery-codes"
ENV KC_DB=postgres
# Install custom providers
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
# change these values to point to a running postgres instance
ARG DBHOST
ARG DBUSERNAME
ARG DBPASSWORD
# ARG DBSCHEMA
ARG HOSTNAME
ARG DBNAME

ENV KC_DB_URL_HOST=$DBHOST
ENV KC_DB_USERNAME=$DBUSERNAME
ENV KC_DB_PASSWORD=$DBPASSWORD
# ENV KC_DB_SCHEMA=$DBSCHEMA
ENV KC_HOSTNAME=$HOSTNAME
ENV KC_DB_URL_DATABASE=$DBNAME
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]